/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-error-container': '#93000a',
        'surface-dim': '#d8dadc',
        'on-primary-fixed-variant': '#07497d',
        'on-primary-fixed': '#001c37',
        'surface': '#f7f9fb',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'primary': '#00355f',
        'on-tertiary-container': '#b2bad3',
        'on-error': '#ffffff',
        'surface-tint': '#2d6197',
        'on-background': '#191c1e',
        'primary-container': '#0f4c81',
        'surface-container-highest': '#e0e3e5',
        'on-primary-container': '#8ebdf9',
        'background': '#f7f9fb',
        'on-tertiary-fixed': '#131b2e',
        'secondary': '#0058be',
        'on-tertiary': '#ffffff',
        'surface-container': '#eceef0',
        'secondary-fixed-dim': '#adc6ff',
        'tertiary-container': '#424a5f',
        'primary-fixed-dim': '#a0c9ff',
        'inverse-on-surface': '#eff1f3',
        'primary-fixed': '#d2e4ff',
        'tertiary-fixed': '#dae2fd',
        'inverse-surface': '#2d3133',
        'on-secondary-fixed-variant': '#004395',
        'secondary-container': '#2170e4',
        'on-primary': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'on-secondary-container': '#fefcff',
        'outline': '#727780',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'secondary-fixed': '#d8e2ff',
        'on-surface': '#191c1e',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#42474f',
        'outline-variant': '#c2c7d1',
        'tertiary-fixed-dim': '#bec6e0',
        'tertiary': '#2c3348',
        'on-tertiary-fixed-variant': '#3f465c',
        'surface-bright': '#f7f9fb',
        'inverse-primary': '#a0c9ff',
        'on-secondary-fixed': '#001a42',
        'surface-variant': '#e0e3e5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        gutter: '24px',
        base: '8px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'section-gap': '120px',
      },
      fontFamily: {
        body: ['Inter', 'sans-serif'],
        headline: ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'display-lg': ['60px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
